- name:Deploy to tomcat
  hosts:web
  become:yes
  tasks:
    - name: copy war file to tomcat
      copy:
        src:"/var/snap/jenkins/common/workspace/webapp/target/ansible.war"
        dest:"/opt/tomcat/webapps/ansible.war"
        remote_src: no
       
    - name: restart tomcat
      systemd:
        name:tomcat
        state:restarted
   
   
   
   
   
   
   
   
   
   
   
   
  
