- name: Deploy to tomcat
  hosts: web
  become: yes
  tasks:
    - name: copy war file to tomcat
      copy:
        src: "/var/snap/jenkins/4874/workspace/ans/target/ansible.war"
        dest: "/opt/tomcat/webapps/ansible.war"
        remote_src: no
       
    - name: restart tomcat manually 
      shell: "/opt/tomcat/bin/shutdown.sh && sleep 5"
   
   
   
   
   
   
   
   
   
   
   
   
  
